name: Monthly Cron Job

on:
  schedule:
    # Runs at midnight UTC on the first of every month
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  trigger-api:
    runs-on: ubuntu-latest
    steps:
      - name: update pool closures
        run: |
          curl -X POST https://vercel-vancouver-pools-proxy.vercel.app/api/manual/populatePoolClosures
